packages:
  - packages/*
  - packages/create-svelte-kitty/template

allowBuilds:
  better-sqlite3: true
  esbuild: false

updateConfig:
  ignoreDependencies:
    - svelte-form-enhanced # deprecated
    - '@sveltejs/vite-plugin-svelte' # 6
    - tailwindcss # 3
    - vite # 7

overrides:
  '@sveltejs/vite-plugin-svelte>vite': '^7'
